# +-------------------------------------------------------------------------
# | Copyright (C) 2019 MacroSAN, Inc.
# +-------------------------------------------------------------------------
# | Licensed under the Apache License, Version 2.0 (the "License");
# | you may not use this work except in compliance with the License.
# | You may obtain a copy of the License in the LICENSE file, or at:
# |
# | http://www.apache.org/licenses/LICENSE-2.0
# |
# | Unless required by applicable law or agreed to in writing, software
# | distributed under the License is distributed on an "AS IS" BASIS,
# | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# | See the License for the specific language governing permissions and
# | limitations under the License.
# +-------------------------------------------------------------------------

# In production, this needs to be in separate files.

# For StatefulSet validation
kind: Service
apiVersion: v1
metadata:
  name: csi-macrosan-controller
  namespace: kube-system
  labels:
    app: "csi-macrosan"
    role: "controller"
    csi: "v1.0.0"
    owner: "NF"
spec:
  selector:
    app: "csi-macrosan"
    role: "controller"
    csi: "v1.0.0"
    owner: "NF"
  ports:
    - name: dummy
      port: 12345
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-macrosan-controller
  namespace: kube-system
spec:
  serviceName: "csi-macrosan-controller"
  selector:
    matchLabels:
      app: "csi-macrosan"
      role: "controller"
      csi: "v1.0.0"
      owner: "NF"
  replicas: 1
  template:
    metadata:
      labels:
        app: "csi-macrosan"
        role: "controller"
        csi: "v1.0.0"
        owner: "NF"
    spec:
      serviceAccount: csi-macrosan-controller
      containers:
      - name: csi-provisioner
        image: quay.io/k8scsi/csi-provisioner:v1.0.1
        args:
        - "--provisioner=csi-macrosan"
        - "--csi-address=$(ADDRESS)"
        - "--connection-timeout=60s"
        - "--v=5"
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy
      - name: csi-attacher
        image: quay.io/k8scsi/csi-attacher:v1.0.1
        args:
        - "--v=5"
        - "--csi-address=$(ADDRESS)"
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy
      - name: csi-macrosan
        image: macrosan/csi-macrosan:v1.0.0
        args :
        - "--nodeid=$(NODE_ID)"
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--v=5"
        - "--drivername=csi-macrosan"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix://var/lib/csi/sockets/pluginproxy/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy
        - name: server-config
          mountPath: /var/log/mconfig
      volumes:
      - name: socket-dir
        emptyDir:
      - name: server-config
        hostPath:
          path: /var/log/contconfig
          type: DirectoryOrCreate
     
    


      
