# +-------------------------------------------------------------------------
# | Copyright (C) 2019 MacroSAN, Inc.
# +-------------------------------------------------------------------------
# | Licensed under the Apache License, Version 2.0 (the "License");
# | you may not use this work except in compliance with the License.
# | You may obtain a copy of the License in the LICENSE file, or at:
# |
# | http://www.apache.org/licenses/LICENSE-2.0
# |
# | Unless required by applicable law or agreed to in writing, software
# | distributed under the License is distributed on an "AS IS" BASIS,
# | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# | See the License for the specific language governing permissions and
# | limitations under the License.
# +-------------------------------------------------------------------------

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-macrosan-controller
  namespace: kube-system
  labels:
    app: "csi-macrosan"
    role: "controller"
    csi: "v1.0.0"
    owner: "NF"

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-macrosan-provisioner
  labels:
    app: "csi-macrosan"
    role: "controller"
    tier: "provisioner"
    csi: "v1.0.0"
    owner: "NF"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-macrosan-attacher
  labels:
    app: "csi-macrosan"
    role: "controller"
    tier: "attacher"
    csi: "v1.0.0"
    owner: "NF"
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-macrosan-controller
  labels:
    app: "csi-macrosan"
    role: "controller"
    csi: "v1.0.0"
    owner: "NF"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      app: "csi-macrosan"
  - matchLabels:
      role: "controller"
  - matchLabels:
      csi: "v1.0.0"
  - matchLabels:
      owner: "NF"
rules: []

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-macrosan-controller
  labels:
    app: "csi-macrosan"
    role: "controller"
    csi: "v1.0.0"
    owner: "NF"
subjects:
  - kind: ServiceAccount
    name: csi-macrosan-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-macrosan-controller
  apiGroup: rbac.authorization.k8s.io
